version: '3.9'

services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_DATABASE: mysite_db
      MYSQL_USER: mysite_user
      MYSQL_PASSWORD: mysite_pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - docker/.env.prod
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/app/static
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/selfsigned.crt:/etc/nginx/selfsigned.crt
      - ./docker/nginx/selfsigned.key:/etc/nginx/selfsigned.key
    depends_on:
      - web

volumes:
  db_data: