services:
  db:
    image: mariadb:11
    restart: always
    env_file:
      - .env.prod
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    image: django-web:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../:/app
    env_file:
      - .env.prod
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/selfsigned.crt:/etc/nginx/selfsigned.crt
      - ./nginx/selfsigned.key:/etc/nginx/selfsigned.key
    depends_on:
      - web

volumes:
  db_data:
