services:
  db:
    container_name: "${DB_CONTAINER_NAME}"
    image: mariadb:11
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      #test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      test: [ "CMD-SHELL", "healthcheck.sh --connect --innodb_initialized" ]
      interval: 10s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1G

  web:
    container_name: "${WEB_CONTAINER_NAME}"
    image: django-web:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  
  nginx:
    container_name: "${NGINX_CONTAINER_NAME}"
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/selfsigned.crt:/etc/nginx/selfsigned.crt
      - ./nginx/selfsigned.key:/etc/nginx/selfsigned.key
    depends_on:
      - web
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

volumes:
  db_data:

networks:
  app-network: