apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: myweb
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: kube-control1
    path: /mnt/data/myweb-db